type Query {    
    """
    Retrieve auth permission info using given name
    """
    authPermission(name: String!): AuthPermission

    """
    Retrieve all auth permission info
    """
    authPermissions: [AuthPermission]

    """
    Retrieve auth role info using given name
    """
    authRole(name: String!): AuthRole

    """
    Retrieve all auth role info
    """
    authRoles: [AuthRole]
}

type Mutation {
    """
    create new auth role
    """
    createAuthRole(name: String!, desc: String!): AuthRole

    """
    modify existing auth role
    """
    modifyAuthRole(name: String!, desc: String, permissions: [String]): AuthRole

    """
    create new auth permission
    """
    createAuthPermission(name: String!, desc: String!): AuthPermission

    """
    modify existing auth permission
    """
    modifyAuthPermission(name: String!, desc: String!): AuthPermission
}