type AuthRole {
  """
  name of the role
  """
  name: String!

  """
  description of the role
  """
  desc: String!

  """
  permissions assigned to the role
  """
  permissions: [AuthPermission]!
}

type AuthPermission {
  """
  name of the role
  """
  name: String!

  """
  description of the role
  """
  desc: String!
}
