scalar EmailAddress
scalar PhoneNumber

type User {
    """
    email of the user
    """
    email: EmailAddress!

    """
    active state of the user
    """
    isActive: Boolean

    """
    phone number of the user
    """
    phone: PhoneNumber

    """
    first name of the user
    """
    firstName: String

    """
    middle name of the user
    """
    middleName: String

    """
    last name of the user
    """
    lastName: String

    """
    auth roles of the user
    """
    authRoles: [String]! @hasAuthRole(roles: ["account.admin"])

    """
    auth permission of the user
    """
    authPermissions: [String]!
}

type AuthPayload {
    user: User!
}
