scalar Email
scalar PhoneNumber

type User {
    """
    email of the user
    """
    email: Email!

    """
    active state of the user
    """
    isActive: Boolean

    """
    phone number of the user
    """
    phone: PhoneNumber

    """
    first name of the user
    """
    firstName: String

    """
    middle name of the user
    """
    middleName: String

    """
    last name of the user
    """
    lastName: String

    """
    auth roles of the user
    """
    authRoles: [String]!

    """
    auth permission of the user
    """
    authPermissions: [String]!
}

"""
Account service provide caller with abilities listed below:
1. Find user info
"""
type Query {
    """
    Retrieve user info with given id
    """
    User(email: Email!): User
}

"""
Expected user input type for signing up
"""
input UserInput {

    """
    email of the user
    """
    email: Email!

    """
    phone number of the user
    """
    phone: PhoneNumber!

    """
    first name of the user
    """
    firstName: String!

    """
    middle name of the user
    """
    middleName: String

    """
    last name of the user
    """
    lastName: String!
}

type AuthPayload {
    user: User!
    token: String!
}

"""
Mutation methods of account service
"""
type Mutation {

    """
    Sign up new user
    """
    signup(email: Email!, password: String!): AuthPayload
}
